/**:
  ros__parameters:
    frames/odom: dlio_odom
    frames/baselink: base_link
    frames/lidar: front_lidar_link
    frames/imu: imu_link

    extrinsics/baselink2imu/t: [0.34629,  -0.00914,  0.04218]
    extrinsics/baselink2imu/R: [ 0.,  0.,  1.,
                                 1.,  0.,  0.,
                                 0.,  1.,  0. ]
    extrinsics/baselink2lidar/t: [0.33767,  0.000,  0.08134]
    extrinsics/baselink2lidar/R: [ 0.,  0.,  1.,
                                   1.,  0.,  0.,
                                   0.,  1.,  0. ]
    # odom/geo/Kp: 4.0 # 6.5 # 5.1
    # odom/geo/Kv: 3.5 # 4.52
    # odom/geo/Kq: 4.5 # 4.0
    # odom/geo/Kab: 3.5 # 2.25
    # odom/geo/Kgb: 1.2 # 1.0
    # odom/geo/abias_max: 3.0 # 5.0
    # odom/geo/gbias_max: 0.3 # 0.5


    odom/gicp/kCorrespondences: 11
    odom/preprocessing/voxelFilter/res: 0.2
    odom/preprocessing/cropBoxFilter/size: 0.2