#!/usr/bin/env python3
"""Generate one-axis-at-a-time (OFAT) terrainAnalysis parameter variants.

For each (param, value) in axes.yaml this writes a variant YAML that is a FULL copy of the
baseline `terrainAnalysis: ros__parameters:` block with exactly ONE key changed.

Why the full block (do not "optimize" to a single-key file): terrain_analysis is launched
with this file as the node's ONLY params source, and it declares every parameter with a C++
default (terrainAnalysis.cpp declare_parameter<T>(name, <c++ default>)) then get_parameter()s
it back. Any key absent from the params file silently keeps the C++ default -- and those
defaults DIFFER from navigation_a2.yaml (e.g. decayTime 2.0 vs 10.0, vehicleHeight 1.5 vs 0.5,
minBlockPointNum 10 vs 20, maxRelZ 0.2 vs 1.5). A single-key file would therefore change ~9
parameters at once, breaking the one-axis-at-a-time premise. This is the same dead-key trap
documented for far_planner in docs/far_planner_tuning.md section 1.

Outputs (under --out, default scripts/terrain_sweep/variants/):
  baseline.yaml            unchanged baseline block (shared reference variant)
  <param>__<value>.yaml    one key changed
  manifest.json            machine-readable sweep map consumed by analyze.py
"""
import argparse
import copy
import json
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not found. Run inside the a2_ros_dev container (ROS 2 ships PyYAML).")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))


def value_token(v):
    """Filesystem-friendly token for a grid value (0.15 -> '0.15', -0.4 -> '-0.4', 0.0 -> '0')."""
    if isinstance(v, bool):
        return str(v).lower()
    if isinstance(v, float):
        return "%g" % v
    return str(v)


def dump_block(ns, params, path):
    """Write {ns: {ros__parameters: params}} preserving key order and ROS yaml conventions."""
    with open(path, "w") as f:
        f.write("# AUTO-GENERATED by gen_variants.py -- do not edit by hand.\n")
        yaml.safe_dump(
            {ns: {"ros__parameters": params}},
            f,
            sort_keys=False,
            default_flow_style=False,
        )


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--axes", default=os.path.join(SCRIPT_DIR, "axes.yaml"),
                    help="sweep spec (default: scripts/terrain_sweep/axes.yaml)")
    ap.add_argument("--out", default=os.path.join(SCRIPT_DIR, "variants"),
                    help="output dir for variant yamls + manifest.json")
    args = ap.parse_args()

    spec = yaml.safe_load(open(args.axes))
    ns = spec.get("node_namespace", "terrainAnalysis")

    base_path = spec["baseline_config"]
    if not os.path.isabs(base_path):
        base_path = os.path.join(REPO_ROOT, base_path)
    base_doc = yaml.safe_load(open(base_path))
    if ns not in base_doc or "ros__parameters" not in base_doc[ns]:
        sys.exit(f"'{ns}: ros__parameters:' not found in {base_path}")
    base = base_doc[ns]["ros__parameters"]

    os.makedirs(args.out, exist_ok=True)

    # Shared baseline reference variant (full block, unchanged).
    dump_block(ns, base, os.path.join(args.out, "baseline.yaml"))

    axes_out = []
    n_variants = 0
    for param, grid in spec["axes"].items():
        if param not in base:
            sys.exit(f"axes.yaml param '{param}' is not in the baseline terrainAnalysis block")
        base_val = base[param]
        # Keep the declared type stable: if the baseline value is an int (declare_parameter<int>),
        # a grid value written as 0.0 would be a float and trip a ROS type-mismatch. Coerce.
        points = []
        for v in grid:
            if isinstance(base_val, bool):
                pass  # leave bools as-is
            elif isinstance(base_val, int) and not isinstance(base_val, bool):
                v = int(v)
            elif isinstance(base_val, float):
                v = float(v)
            if v == base_val:
                points.append({"value": v, "variant": "baseline"})
                continue
            params = copy.deepcopy(base)
            params[param] = v
            name = f"{param}__{value_token(v)}"
            dump_block(ns, params, os.path.join(args.out, name + ".yaml"))
            points.append({"value": v, "variant": name})
            n_variants += 1
        axes_out.append({"param": param, "baseline": base_val, "points": points})

    manifest = {
        "baseline_config": base_path,
        "node_namespace": ns,
        "baseline_variant": "baseline",
        "baseline_params": base,
        "axes": axes_out,
    }
    with open(os.path.join(args.out, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    total = n_variants + 1
    print(f"Generated {total} configs ({n_variants} variants + baseline) for "
          f"{len(axes_out)} axes -> {args.out}")
    for ax in axes_out:
        vals = ", ".join(value_token(p["value"]) for p in ax["points"])
        print(f"  {ax['param']:<16} baseline={value_token(ax['baseline'])}  grid=[{vals}]")


if __name__ == "__main__":
    main()
